name: "MediaShare"
guid: "613657e0-25b9-4d58-9f4d-1496726b0532"
imageUrl: https://raw.githubusercontent.com/interlock/jellyfin_share/main/mediashare.svg
version: 1
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "interlock"
overview: "Share your Media Library with others"
description: >
  Share your Media Library with others

category: "Sharing"
artifacts:
  - "JellyfinMediaShare.dll"
changelog: |-
  - Meh